---
title: "International Climate Policy - Homework 2"
author: "Amartya Kumar Sinha"
date: "2024-02-01"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Amartya Kumar Sinha/OneDrive - The University of Chicago/IntlClimatePolicy_PPHA39930/Assignments/Assn2_IntlClimatePolicy") 
library(dplyr)
library(ggplot2)
```

```{r}
rep_nomiss <- read.csv("icp_indiv_2_dg2011_rep_nomiss.csv")
ave_temp <- read.csv("icp_indiv_2_county_avetemp.csv")
```

# Question 1
### Taking population weighted average across all temperature variables for the entire country

```{r}
# Creating a new dataframe where each row is a temperature range and its population-weighted average
temp_vars <- grep("tday", names(rep_nomiss), value = TRUE)

pop_weighted_avg <- sapply(temp_vars, function(x) weighted.mean(rep_nomiss[[x]], rep_nomiss$population, na.rm = TRUE))
```

## 1. a) 
### Plotting histogram of number of days within each temperature range

```{r}

labels <- c("<10", "10–20", "20–30", "30–40", "40–50", "50–60", "60–70", "70–80", "80–90", ">90")

# Now, let's plot the histogram
barplot(pop_weighted_avg, 
        main = "Population-Weighted Average Number of Days in \nEach Temperature Range (1968-2002 average)", 
        ylab = "", 
        xlab = "Annual distribution of daily mean temperatures (F)", 
        ylim = c(0, 80), 
        names.arg = labels, 
        las = 2, col = "lightyellow")

# Add lines stretching across the graph from the x-axis
abline(h = seq(0, max(pop_weighted_avg), by = 10), col = "gray", lty = "dotted")
```
## 1. b)
### 




